### ISSUE TITLE
create-review API 

### ISSUE THREAD

**Issue by lespaceman** [Kites-Foundation/hellomunnar-api#26]
create-review API requires a type field to sort reviews based on different categories such as Destinations, Activities, or Amenities.

Schema 

`{
  "userId": "asdaly12hbldahbsdl21bekd",
  "type": "destinations",
  "Id": "D-047",
  "title": "Very GOod Experience",
  "rating": 5,
  "content": "Very good experience",
  "status": "pending",
  "profileImgUrl": "Image Urls as a json : https://cdn.hellomunnar.in/userContent/image.png"
}`

**Comment by dauntlessnomad** [comment]
This api is already present. Please check swagger

**Comment by lespaceman** [comment]
@tomahawk-pilot there is no type field to filter reviews for different categories
