### ISSUE TITLE
list-review API

### ISSUE THREAD

**Issue by lespaceman** [Kites-Foundation/hellomunnar-api#27]
**This API should accept the following parameters:** 
- type (used to identify categories such as destinations, activities, amenities)
- id (eg: id of a destination or activity)
- count (number of reviews needed in the response)

**This API should provide a list of reviews with the following keys:** 
- userId
- profileImgUrl
- reviewId
- title
- content
- rating
- date

**Comment by dauntlessnomad** [comment]
these are already present
send the filter as  a json to /api/v1/reviews/all-reviews 
{
  "userId": null,
  "destinationId": null,
  "facilityId": null,
  "activityId": null,
  "typeId": null,
  "status": null,
  "page": null,
  "offset": null,
  "limit": null
}

are the queries accepted by the api

**Comment by lespaceman** [comment]
@tomahawk-pilot looks like we have all the queries for request, can you confirm if we have all the required info in response?

**Comment by dauntlessnomad** [comment]
yes @lespaceman
